feat: docker install test

diff --git a/.github/workflows/migrate-db.yaml b/.github/workflows/migrate-db.yaml
--- a/.github/workflows/migrate-db.yaml
+++ b/.github/workflows/migrate-db.yaml
@@ -21,8 +21,12 @@ jobs:
   migrate:
     runs-on: ${{ inputs.use_private_agent == true && 'self-hosted' || 'ubuntu-22.04' }}
     environment: ${{ inputs.environment }}-cd
-    permissions:
-      contents: read
+    services:
+      docker:
+        image: docker:dind
+        options: --privileged --shm-size=2g
+        volumes:
+          - /var/run/docker.sock:/var/run/docker.sock:ro
 
     steps:
       - name: checkout
@@ -32,8 +36,8 @@ jobs:
         run: |
           apt-get update
           apt-get install -y docker.io
-          systemctl start docker
-          ystemctl enable docker
+          # systemctl start docker
+          # ystemctl enable docker
 
       - name: Verify Docker Installation
         run: docker --version
@@ -42,13 +46,25 @@ jobs:
         run: |
           docker run hello-world
 
-      - name: Migrate DB Schema
-        run: |-
-          set -e
-          ./scripts/run_flyway_on_azure.sh migrate db PROD-IO schema/migrations "${{ env.SCHEMA_NAME }}" \
-            && echo "Migration successful" \
-            || { echo "Migration failed"; exit 1; }
-        shell: bash
-        env:
-          # THIS IS THE PRODUCTION SCHEMA NAME, SO PLEASE DON'T CHANGE IT
-          SCHEMA_NAME: DeveloperPortalServiceData
+      # - name: Azure Login
+      #   uses: azure/login@v2 # v2.0.0
+      #   env:
+      #     ARM_USE_OIDC: true
+      #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+      #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+      #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+      #   with:
+      #     client-id: ${{ env.ARM_CLIENT_ID }}
+      #     tenant-id: ${{ env.ARM_TENANT_ID }}
+      #     subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
+
+      # - name: Migrate DB Schema
+      #   run: |-
+      #     set -e
+      #     ./scripts/run_flyway_on_azure.sh migrate db PROD-IO schema/migrations "${{ env.SCHEMA_NAME }}" \
+      #       && echo "Migration successful" \
+      #       || { echo "Migration failed"; exit 1; }
+      #   shell: bash
+      #   env:
+      #     # THIS IS THE PRODUCTION SCHEMA NAME, SO PLEASE DON'T CHANGE IT
+      #     SCHEMA_NAME: DeveloperPortalServiceData
